// One-time: creates the Ed25519 key pair that signs Hemisphere content.
//   npm run content:keygen
// The PRIVATE key stays on the staff PC (never commit it). The PUBLIC key is written into the launcher source.
import { generateKeyPairSync } from 'node:crypto'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { defaultKeyPath } from './keyPath.ts'

const keyPath = process.env.HEMI_SIGNING_KEY ?? defaultKeyPath()
if (existsSync(keyPath) && !process.argv.includes('--force')) {
  console.error(`A signing key already exists at ${keyPath}.\nRefusing to overwrite it (players' launchers trust the current key). Use --force only if you know why.`)
  process.exit(1)
}

const { privateKey, publicKey } = generateKeyPairSync('ed25519')
mkdirSync(dirname(keyPath), { recursive: true })
writeFileSync(keyPath, privateKey.export({ type: 'pkcs8', format: 'pem' }), { mode: 0o600 })

const spki = (publicKey.export({ type: 'spki', format: 'der' }) as Buffer).toString('base64')
const target = join(import.meta.dirname, '..', '..', 'src', 'main', 'core', 'remote', 'publicKey.ts')
mkdirSync(dirname(target), { recursive: true })
writeFileSync(
  target,
  `/** Ed25519 public key (SPKI, base64) that verifies Hemisphere content. Generated by tools/content/keygen.ts. */\nexport const CONTENT_PUBLIC_KEY = '${spki}'\n`,
)

console.log(`Private key: ${keyPath}   <- BACK THIS UP somewhere safe. Never commit or share it.`)
console.log(`Public key written to src/main/core/remote/publicKey.ts`)
