/** Ed25519 public key (SPKI, base64) that verifies Hemisphere content. Generated by tools/content/keygen.ts. */
export const CONTENT_PUBLIC_KEY = 'MCowBQYDK2VwAyEA+wQdi8YUFbXGhXFFnuWBC4pmbgPhwnwiSBcPO4nM6YQ='
